- name: Install ZSH
  apt: name=zsh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - dotfiles
    - productivity
    - zsh
- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Remove .zshrc so dotfile install work
  shell: rm ~/.zshrc
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
- name: Install zsh-completions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
